DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS "payments";
DROP TABLE IF EXISTS "customers";
DROP TABLE IF EXISTS "orderDetails";
DROP TABLE IF EXISTS "orders";

DROP TABLE IF EXISTS "stock";

DROP TABLE IF EXISTS "genres";
DROP TABLE IF EXISTS "booksByAuthors";
DROP TABLE IF EXISTS "authors";
DROP TABLE IF EXISTS "books";